# Generated by Django 4.2 on 2025-05-27 12:46

import apps.claims.enums
import apps.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('claim_date', models.DateTimeField(blank=True, null=True)),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', apps.fields.EnumSmallIntegerField(enum_class=apps.claims.enums.ClaimStatus)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
