# Generated by Django 4.2 on 2025-05-29 09:01

import apps.claims.enums
import apps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_claim_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=apps.fields.EnumSmallIntegerField(default=apps.claims.enums.ClaimStatus['PENDING'], enum_class=apps.claims.enums.ClaimStatus),
        ),
    ]
