# Generated by Django 4.2 on 2025-05-29 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
