# Generated by Django 4.2 on 2025-05-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_alter_policy_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='price',
        ),
        migrations.AddField(
            model_name='policy',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
